package transformation

import transformation.transformations.column.Base64Imp.Base64Instance
import transformation.transformations.column.CaseLetterImp.CaseLetterInstance
import transformation.transformations.column.CatalogImp.CatalogInstance
import transformation.transformations.column.CharacterTrimmerImp.CharacterTrimmerInstance
import transformation.transformations.column.CommaDelimiterImp.CommaDelimiterInstance
import transformation.transformations.column.CopyColumnImp.CopyColumnInstance

object Transformations extends Base64Instance
  with CaseLetterInstance
  with CatalogInstance
  with CharacterTrimmerInstance
  with CommaDelimiterInstance
  with CopyColumnInstance
